# Generated by Django 4.1.3 on 2022-12-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAuth', '0009_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default='default.png', upload_to='media/profile_pics'),
        ),
    ]
