# Generated by Django 4.1.3 on 2022-12-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibreria', '0002_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
