# Generated by Django 4.1.3 on 2022-12-15 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLibreria', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
